[package]
name = "northstar-hasher"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "RAGE/JOAAT string hash utility compatible with legacy hasher.exe CLI."
build = "build.rs"

[build-dependencies]
winres = "0.1"

[[bin]]
name = "northstar-hasher"
path = "src/main.rs"

[dependencies]

northstar-cli = { path = "../../shared/northstar_cli" }
