[package]
name = "northstar-ytyp-packer"
version = "0.2.0"
edition = "2021"
build = "build.rs"
description = "North Star Y-Type Properties packer"
license = "MIT"

[dependencies]
northstar-nef8 = { path = "../../shared/northstar_nef8" }
northstar-cli = { path = "../../shared/northstar_cli" }
blake3 = "1.5"
flate2 = "1.0"
serde_json = "1.0"

[build-dependencies]
winres = "0.1"

[lib]
name = "northstar_ytyp_packer"
path = "src/lib.rs"

[[bin]]
name = "northstar-ytyp-packer"
path = "src/main.rs"
